language: go
go: '1.13'
env:
  global:
    - GO111MODULE=on
script: go test -race -coverprofile=coverage.txt -covermode=atomic ${gobuild_args} ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)